---
- name: Set up Raspberry Pi Fleet
  hosts: orion, castor
  become: true
  vars_files:
    - credentials.yml
  vars:
    home_directory: "/home/{{ ansible_user }}"
    emacs_build_processes: "{{ ansible_processor_vcpus }}"
    venv_path: "/opt/jupyter"

  roles:

    #######
    # RPi #
    #######

    - { role: zero-2w-setup, tags: [ zero2 ] }

    #########################
    # Network & Basic Tools #
    #########################

    - { role: apt-update, tags: [foundational, apt-update] }
    - { role: tailscale, tags: [foundational,  tailscale] }
    - { role: seafile-client, tags: [foundational, seafile] }
    - { role: sync-notify, tags: [foundational, sync-notify] }
    - { role: shell, tags: [foundational,  shell] }
    - { role: babashka, tags: [foundational, babashka] }
    - { role: wifi-networks, tags: [network, wifi-networks], wifi_interface: 'wlan0' }
    - { role: wifi-access-point, tags: [network, wifi-access-point] }
    - { role: usb-gadget, tags: [network, usb-gadget] }

    #####################
    # Emacs Environment #
    #####################

    - { role: emacs-build, tags: [emacs, emacs-build], emacs_version: '30.1' }
    - { role: spacemacs, tags: [emacs, spacemacs] }
    - { role: tmux-service, tags: [emacs, tmux-service] }
    - { role: aspell, tags: [emacs, aspell] }

    ######################
    # Diogenes & the TLG #
    ######################

    - { role: tlg-data, tags: [tlg, tlg-data] }
    - { role: diogenes, tags: [tlg, diogenes], diogenes_server_interface: "lo" }

    ###################
    # Text Processing #
    ###################

    - { role: texlive, tags: [text, texlive] }
    - { role: pandoc, tags: [text, pandoc], pandoc_version: '3.4' }
    - { role: zettel-composer, tags: [text, zettel-composer] }
    - { role: premarkable, tags: [text, premarkable], premarkable_http_port: "8082" }

    ################
    # My git stuff #
    ################

    - { role: git-with-creds, vars: { repo_name: bibs }, tags: [git-pvt-repo, bibs] }
    - { role: git-with-creds, vars: { repo_name: profile }, tags: [git-pvt-repo, profile-src, profile] }
    - { role: profile-links, tags: [git-pvt-repo, profile-links, profile] }


    ######################
    # Presentation & Gui #
    ######################

    - { role: keyboard-layout, tags: [gui, keyboard-layout], kb_layout: "us", kb_variant: "intl" }
    - { role: i3, tags: [gui, i3], i3_mod_key: 'Mod4' }
    - { role: key-config, tags: [gui, key-config] }
    - { role: natural-scroll, tags: [gui, natural-scroll], device: 'MX Anywhere 2 Mouse' }
    - { role: revealjs, tags: [revealjs], revealjs_http_port: '8001' }
    - { role: kiosk, tags: [gui, kiosk], kiosk_url: "http://localhost:8001" }
    - { role: uxplay, tags: [gui, uxplay] }

    #########
    # Fonts #
    #########

    - { role: ia-duospace-font, tags: [gui, fonts, ia-duospace] }
    - { role: eb-garamond-font, tags: [fonts, text, eb-garamond] }
    - { role: rokkitt-font, tags: [gui, fonts, rokkitt] }


    ##########################################
    # Artificial Intelligence & Data Science #
    ##########################################

    - { role: jupyter-notebook, tags: [ai, jupyter-notebook]}
    - { role: llamaindex, tags: [ai, llamaindex]}

    ####################
    # External Storage #
    ####################

    - { role: external-storage, tags: [external-storage],
        volume_uuid: 'fbec5597-30c0-4e52-8d2d-bb8bd1d54ab3', mount_point: "/mnt/external" }

    ############
    # Routines #
    ############

    - { role: poweroff, tags: poweroff }

