---
- name: Install X11, i3, Chromium, and unclutter (to hide the mouse cursor)
  apt:
    name:
      - xorg
      - i3
      - chromium-browser
      - unclutter
      - lightdm
    state: present

- name: Create i3 config directory
  file:
    path: /home/{{ ansible_user }}/.config/i3
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Configure i3 to launch Chromium in kiosk mode
  copy:
    dest: /home/{{ ansible_user }}/.config/i3/config
    content: |
      # i3 config file
      # Disable workspace switching
      bindsym $mod+Shift+q exec --no-startup-id "pkill X"

      # Launch Chromium in kiosk mode at startup
      exec --no-startup-id "chromium-browser --noerrdialogs --disable-translate --disable-infobars --kiosk {{ kiosk_url | default('http://localhost:8001') }}"

      # Hide mouse cursor when idle
      exec --no-startup-id "unclutter"

      # Optional: Prevent screen from going to sleep
      # exec --no-startup-id "xset s off"
      # exec --no-startup-id "xset s noblank"
      # exec --no-startup-id "xset -dpms"

    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755


# - name: Set up i3 as the default window manager
#   copy:
#     dest: /home/{{ ansible_user }}/.xinitrc
#     content: |
#       # Start i3 when X11 starts
#       exec i3
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: 0755

# - name: Disable screensaver and power management
#   copy:
#     dest: /etc/xdg/lxsession/LXDE/autostart
#     content: |
#       @xset s off
#       @xset -dpms
#       @xset s noblank
#     owner: root
#     group: root
#     mode: 0644

# - name: Enable autologin for the user
#   copy:
#     dest: /etc/systemd/system/getty@tty1.service.d/autologin.conf
#     content: |
#       [Service]
#       ExecStart=
#       ExecStart=-/sbin/agetty --autologin {{ ansible_user }} --noclear %I $TERM
#     owner: root
#     group: root
#     mode: 0644

# - name: Enable auto-start of X11 on login
#   copy:
#     dest: /home/{{ ansible_user }}/.bash_profile
#     content: |
#       if [ -z "$DISPLAY" ] && [ $(tty) = /dev/tty1 ]; then
#         startx
#       fi
#     owner: "{{ ansible_user }}"
#     group: "{{ ansible_user }}"
#     mode: 0755

- name: Configure LightDM for autologin inside [Seat:*] section
  blockinfile:
    path: /etc/lightdm/lightdm.conf
    marker: "# MANAGED BY ANSIBLE - AUTLOGIN"
    block: |
      autologin-user={{ ansible_user }}
    insertafter: '^\[Seat:\*\]'

- name: Comment out existing autologin-session entries
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^(?!#).*autologin-session='
    line: '#autologin-session='
    state: present
    backrefs: yes


- name: Set default session to i3 inside [Seat:*] section
  blockinfile:
    path: /etc/lightdm/lightdm.conf
    marker: "# MANAGED BY ANSIBLE - SESSION"
    block: |
      autologin-session=i3
    insertafter: '^\[Seat:\*\]'


- name: Restart LightDM to apply changes
  service:
    name: lightdm
    state: started

# não parece ter funcionado
# - name: Set Raspberry Pi to boot into GUI
#   systemd:
#     name: graphical.target
#     enabled: yes
#     state: started

- name: Change default target to graphical.target
  file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
  tags: xxx
