---
- name: Install X11, i3, Chromium, and unclutter (to hide the mouse cursor)
  apt:
    name:
      - xorg
      - i3
      - chromium-browser
      - unclutter
      - lightdm
    state: present


- name: Create i3 configuration file for launching Chromium in kiosk mode
  copy:
    dest: /home/{{ ansible_user }}/.config/i3/kiosk.conf
    content: |
      # i3 custom config for kiosk mode
      # Disable workspace switching
      # bindsym $mod+Shift+q exec --no-startup-id "pkill X"

      # Launch Chromium in kiosk mode at startup
      exec --no-startup-id "chromium-browser --noerrdialogs --disable-translate --disable-infobars --kiosk {{ kiosk_url | default('http://localhost:8001') }}"

      # Hide mouse cursor when idle
      exec --no-startup-id "unclutter"

      # Optional: Prevent screen from going to sleep
      # exec --no-startup-id "xset s off"
      # exec --no-startup-id "xset s noblank"
      # exec --no-startup-id "xset -dpms"

    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Ensure custom kiosk config is included in i3 config
  lineinfile:
    path: "/home/{{ ansible_user }}/.config/i3/config"
    line: "include /home/{{ ansible_user }}/.config/i3/kiosk.conf"
    insertafter: EOF
    regexp: '^include\s+".*kiosk\.conf"$'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Set default session to i3 inside [Seat:*] section
  blockinfile:
    path: /etc/lightdm/lightdm.conf
    marker: "# MANAGED BY ANSIBLE - KIOSK"
    block: |
      autologin-session=i3
    insertafter: '^\[Seat:\*\]'

- name: Configure LightDM for autologin inside [Seat:*] section
  blockinfile:
    path: /etc/lightdm/lightdm.conf
    marker: "# MANAGED BY ANSIBLE - KIOSK"
    block: |
      autologin-user={{ ansible_user }}
    insertafter: '^\[Seat:\*\]'

- name: Comment out existing autologin-session entries
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^(?!#).*autologin-session='
    line: '#autologin-session='
    state: present
    backrefs: yes

- name: Restart LightDM to apply changes
  service:
    name: lightdm
    state: restarted

