---
# FIXME: not working on startup; works with i3 reload (thus, using `exec_always` for now)
- name: Create i3 configuration file for the keymap
  copy:
    dest: "/home/{{ ansible_user }}/.config/i3/keymap.conf"
    content: |
      exec_always --no-startup-id setxkbmap -option altwin:swap_alt_win,ctrl:nocaps
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

- name: Ensure keymap config is included in i3 config
  lineinfile:
    path: "/home/{{ ansible_user }}/.config/i3/config"
    line: "include /home/{{ ansible_user }}/.config/i3/keymap.conf"
    insertafter: EOF
    regexp: '^include\s+".*keymap\.conf"$'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644

