---
- name: Ensure network-manager is installed
  apt:
    name: network-manager
    state: present
  become: true

- name: Configure Wi-Fi networks in order of priority
  loop: "{{ wifi_networks }}"
  loop_control:
    label: "{{ item.ssid }}"
  nmcli:
    conn_name: "{{ item.ssid }}"
    ifname: "{{ wifi_interface }}"
    type: "wifi"
    ssid: "{{ item.ssid }}"
    wifi_sec:
      psk: "{{ item.psk }}"
      key-mgmt: "wpa-psk"
    autoconnect: yes
    state: present
  become: true

- name: Stop and disable wpa_supplicant to avoid conflicts
  service:
    name: wpa_supplicant
    state: stopped
    enabled: false
  become: true

- name: Restart NetworkManager to apply changes
  service:
    name: NetworkManager
    state: restarted

#---
# - name: Configure WPA Supplicant
#   template:
#     src: wpa_supplicant.conf.j2
#     dest: /etc/wpa_supplicant/wpa_supplicant.conf
#     owner: root
#     group: root
#     mode: '0600'
#   notify: Restart networking

# - name: Ensure wpa_supplicant is enabled and running
#   service:
#     name: wpa_supplicant
#     enabled: yes
#     state: started
