---
- name: Install NodeJS and npm
  apt:
    name:
      - nodejs
      - npm
    state: present

- git:
    repo: "https://github.com/hakimel/reveal.js.git"
    dest: "{{ home_directory}}/src/reveal.js"
    update: yes
  become: false

- name: Install Reveal.JS
  command:
    cmd: npm install
    chdir: "{{ home_directory }}/src/reveal.js"
  become: false

- name: Install Yarn package manager
  npm:
    name: yarn
    global: yes
    state: present
  become: true
  tags: mermaid

- name: Add mermaid via Yarn
  command:
    cmd: yarn add mermaid
    chdir: "{{ home_directory }}/src/reveal.js"
  become: false
  tags: mermaid

- name: Add reveal.js-mermaid-plugin via Yarn
  command:
    cmd: yarn add reveal.js-mermaid-plugin
    chdir: "{{ home_directory }}/src/reveal.js"
  become: false
  tags: mermaid

- name: Ensure Mermaid plugin is symlinked in the dist directory
  file:
    src: "{{ home_directory }}/src/reveal.js/node_modules/reveal.js-mermaid-plugin/plugin/mermaid"
    dest: "{{ home_directory }}/src/reveal.js/plugin/mermaid"
    state: link
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  tags: mermaid

# Adding systemd service for RevealJS

- name: Create systemd service file for RevealJS
  copy:
    dest: /etc/systemd/system/revealjs.service
    content: |
      [Unit]
      Description=RevealJS Presentation Server
      After=network.target

      [Service]
      ExecStart=/usr/bin/npm start -- --port={{ revealjs_http_port | default('8001') }}
      WorkingDirectory={{ home_directory }}/src/reveal.js
      Restart=always
      User={{ ansible_user }}

      [Install]
      WantedBy=multi-user.target

- name: Ensure ownership of Reveal.JS directory and its contents
  file:
    path: "{{ home_directory }}/src/reveal.js"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    recurse: yes

- name: Reload systemd daemon to recognize new service
  command: systemctl daemon-reload

- name: Enable RevealJS service to start on boot
  systemd:
    name: revealjs
    enabled: yes

- name: Start RevealJS service
  systemd:
    name: revealjs
    state: started
